Aplikacja serwerowa i webowa/stamp_server/main_app/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'main_app'
urlpatterns = [
    url(r'^$', views.start_page, name='start_page'),
    url(r'^user_account/', include("user_account.urls", namespace="user_account")),
    url(r'^archives/$', views.archives, name='archives'),
    url(r'^upload/$', views.upload_file, name='upload_file'),
    url(r'^magnet/$', views.magnet_file, name='magnet_file'),
    url(r'^archives/delete/(?P<file_id>[0-9]+)/$', views.delete_file, name='delete_file'),
    url(r'^download/magnet/(?P<file_id>[0-9]+)/$', views.download_magnet_file, name='download_magnet_file'),

    # API
    url(r'^api/login/$', views.api_login, name='api_login'),
    url(r'^api/logout/$', views.api_logout, name='api_logout'),
    url(r'^api/register/$', views.api_register, name='api_register'),
    url(r'^api/del_account/$', views.api_del_account, name='api_del_account'),
    url(r'^api/change_mail/$', views.api_change_mail, name='api_change_mail'),
    url(r'^api/change_password/$', views.api_change_password, name='api_change_password'),
    url(r'^api/archives/$', views.api_archives, name='api_archives'),
    url(r'^api/del_file/$', views.api_delete_file, name='api_delete_file'),
    url(r'^api/upload/$', views.api_upload_file, name='api_upload_file'),
    url(r'^api/download_magnet/$', views.api_download_magnet_file, name='api_download_magnet_file'),
    url(r'^api/check_magnet/$', views.api_check_magnet, name='api_check_magnet'),
    url(r'^api/download_file/$', views.api_download_file, name='api_download_file'),
    url(r'^api/check_magnet2/$', views.api_check_magnet2, name='api_check_magnet2'),
    url(r'^api/download_file2/$', views.api_download_file2, name='api_download_file2'),
]

Aplikacja serwerowa i webowa/stamp_server/stamp_server/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from .settings import MEDIA_ROOT, MEDIA_URL, DEBUG
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('user_account.urls')),
    url(r'^', include('main_app.urls'))  # od razu po wejsci kieruje do main_app.urls
]

if DEBUG:
    # umozliwia serwowanie statycznych plikow z katalogu media
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT,}, name='media'),
    ]

Aplikacja serwerowa i webowa/stamp_server/user_account/urls.py
from django.conf.urls import url

from . import views

app_name = 'user_account'
urlpatterns = [
    url(r'^login/$', views.login_view, name='login_view'),
    url(r'^logout/$', views.logout_view, name='logout_view'),
    url(r'^register/$', views.register_view, name='register_view'),
    url(r'^activate/(?P<username>[\w\d]+)/(?P<activation_code>[\w\d]+)/$',views.activate,name='activate'),
    url(r'^$', views.user_profile, name='user_profile'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^change_email/$', views.change_email, name='change_email'),
    url(r'^account_delete/$', views.account_delete, name='account_delete'),
]

# pierwszy argument (regular expression r'') to adres widoczny dla uzytkownika
# jest niezalezny od name'a :)

Aplikacja serwerowa i webowa/stamp_server/main_app/models.py
# coding=utf-8
from django.db import models
from django.contrib.auth.models import User
import os  # for filename in Documents
import django.utils.timezone as timezone  # data i czas
import hashlib

def user_directory_path(instance, filename):
    # ustawia katalog zapisu pliku
    # rozny dla kazdego uzytkownika
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return '{0}/{1}'.format(instance.owner.id, filename)

class Documents(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="właściciel")
    file = models.FileField(upload_to=user_directory_path, verbose_name="plik")
    timestamp = models.DateTimeField(default=timezone.now)
    hash = models.CharField(max_length=64, unique=True, db_index=True)

    def filename(self):
        # return filename of the file, because field 'file' return path
        # w archives.html z tego korzystam
        return os.path.basename(self.file.name)

class Tokens(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="właściciel")
    key = models.CharField(max_length=64, unique=True)
    timestamp = models.DateTimeField(default=timezone.now)

    @staticmethod
    def generate_key(username, timestamp):
        hasher = hashlib.sha256()
        hasher.update(str(username).encode('utf-8')+str(timestamp).encode('utf-8'))
        return hasher.hexdigest()

    def save(self, *args, **kwargs):
        self.key = self.generate_key(self.user.username, self.timestamp)
        super(Tokens, self).save(*args, **kwargs)

Aplikacja serwerowa i webowa/stamp_server/main_app/forms.py
from django import forms
from .models import Documents

class UploadFileForm(forms.ModelForm):
    # upload pliku do podpisania
    # formularz oparty na modelu Documents
    def __init__(self, *args, **kwargs):
        # musialem przeciazyc kontruktor zeby mozna bylo do formularza przekazac obiekt user'a
        # obiekt user'a potrzebny jest nizej w clean() do walidacji
        self.user = kwargs.pop('user', None)
        super(UploadFileForm, self).__init__(*args, **kwargs)

    def clean(self):
        # odpala sie automatycznie podczas 'form.is_valid()' w views.py
        # waliduje czy plik o takiej samej nazwie juz jest w bazie
        document = self.cleaned_data['file']  # obiekt Documents
        document = str(self.user.id) + "/" + str(document)  # np. '1/plik.txt'
        document = document.replace(" ","_")
        other_the_same = Documents.objects.filter(file=document)
        if other_the_same:
            # jezeli w bazie istnieje juz plik o takiej nazwie
            raise forms.ValidationError("File with the same name exist in database !!!")
        return self.cleaned_data

    class Meta:
        model = Documents  # jaki model
        fields = ('file', )  # jakie pola z modelu ma wziac

class MagnetFileForm(forms.Form):
    # upload pliku magnetycznego
    magnet_file = forms.FileField(label='Plik')  # help_text='' - dodatkowa informacja

    def clean_magnet_file(self):
        magnet_file = self.cleaned_data['magnet_file']
        mime = magnet_file.content_type
        if mime == 'application/octet-stream' and magnet_file.size <= 100:
            # plik jest typu application/octet-stream i ma miec <= 100 bajtow
            return magnet_file
        else:
            # rzucam blad, ale w views.py i tak go nie lapie, bo tam sprawdzam poprawnosc if'em
            raise forms.ValidationError('Bad magnet file !!!')

Aplikacja serwerowa i webowa/stamp_server/main_app/views.py
# coding=utf-8
from __future__ import print_function
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import UploadFileForm, MagnetFileForm
from .models import Documents, Tokens
import os
from stamp_server.settings import MEDIA_ROOT, MEDIA_URL
import hashlib  # generowanie SHA384
from django.core.signing import Signer  # podpisywanie pliku magnetycznego
from django.core.signing import BadSignature
from django.contrib import messages  # powiadomienia, ktore mozna wyswietlic w HTMLu
from django.views.decorators.csrf import csrf_exempt  # wylaczenie CSRF tokenow
from django.http import JsonResponse  # zwracanie JSONow w odpowiedzi
from django.contrib.auth.models import User  # model User
from django.contrib.auth import authenticate  # metoda autoryzacji
from django.core.mail import send_mail  # wysylanie maili
import django.utils.timezone as timezone  # data i czas
from django.http import FileResponse  # zwracanie pliku - API

from stamp_server.settings import EMAIL_HOST_USER  # import maila tej apki

def start_page(request):
    if request.user.is_authenticated:
        # ZALOGOWANY
        upload_form = UploadFileForm(user=request.user)
        magnet_form = MagnetFileForm()
        data = {
            'uploadForm': upload_form,
            'magnetForm': magnet_form
        }
        return render(request, 'main_app/Home_logged.html', data)
    else:
        magnet_form = MagnetFileForm()
        data = {
            'magnetForm': magnet_form
        }
        # NIEZALOGOWANY
        return render(request, 'main_app/Home_notLogged.html', data)

@login_required
def archives(request):
    docs = Documents.objects.filter(owner=request.user)
    # bug - aplikacja nie rozpoznaje czy plik jest fizycznie na dysku
    data = {
        "docs": docs,
        "user": request.user,
        "MEDIA_URL": MEDIA_URL
    }
    return render(request, 'main_app/archives.html', data)

@login_required
def delete_file(request, file_id):
    # usuniecie pliku z archiwum
    user = request.user
    doc = get_object_or_404(Documents, pk=file_id)
    path = 'media/' + str(request.user.id)  # katalog w ktorym sa pliki

    # sprawdzam czy istnieje tez plik magnetyczny do dokumentu
    magnet_filename = str(doc.filename())+"-"+str(doc.timestamp.strftime('%d.%m.%Y-%H:%M'))+".magnet"
    magnet_path = os.path.join(path, magnet_filename)
    if os.path.isfile(magnet_path):
        # usuwam plik magnetyczny
        os.remove(magnet_path)

    if doc.owner == user:
        # usuniecie dokumentu z bazy danych
        doc.delete()

    doc_path = os.path.join(path, os.path.basename(doc.file.name))  # sciezka do dokumentu
    if os.path.isfile(doc_path):
        # usuniecie dokumentu z dysku
        os.remove(doc_path)
    messages.success(request,'Usunięto plik z archiwum.')
    return redirect('main_app:archives')

# --------------   metody pomocnicze    ----------
# obliczanie funkcji skrotu na pliku
def file_sha256(document):
    hasher = hashlib.sha256()  # to jest SHA-2
    for chunk in document.chunks():
        hasher.update(chunk)
    return hasher.hexdigest()

# obliczanie funkcji skrotu na lancuchu znakow
def string_sha256(s):
    hasher = hashlib.sha256()
    hasher.update(s)
    return hasher.hexdigest()

@login_required
def upload_file(request):
    # dodanie pliku do archiwum
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            plik = form.save(commit=False)
            plik.owner = request.user

            # generowanie hash'a
            h = file_sha256(plik.file)
            # timestamp z bazy danych
            ts = plik.timestamp.timestamp()  # zwraca sekundy.milisekundy od 01.01.1970
            ts = str(ts).split(".")[0]  # wybieram z timestampa sekundy
            # hash z h+ts
            hash_h_ts = string_sha256(str(h).encode('utf-8')+str(ts).encode('utf-8'))

            plik.hash = hash_h_ts
            plik.save()
            messages.success(request,'Dodano plik do archiwum.')
            return redirect('main_app:start_page')
        else:
            print("Bad form !!! File with the same name exist in database !!!")
            messages.error(request,'Plik o identycznej nazwie istnieje w archwium. Zmień nazwę.')
            return redirect('main_app:start_page')
    else:
        return redirect('main_app:start_page')


@login_required
def download_magnet_file(request, file_id):
    # pobranie pliku magnetycznego z archiwum
    doc = get_object_or_404(Documents, id=file_id)
    if request.user == doc.owner:
        magnet_filename = str(doc.filename())+"-"+str(doc.timestamp.strftime('%d.%m.%Y-%H:%M'))+".magnet"  # MAGNET FILENAME
        magnet_path = 'media/'+str(request.user.id) + '/' + magnet_filename  # MAGNET FILE PATH

        if not os.path.isfile(magnet_path):
            # jezeli plik magnetyczny nie istnieje jeszcze to go utworz
            magnet = open(magnet_path,'w')
            # podpis pliku
            signer = Signer()  # salt='jakas_sol'
            signed_hash = signer.sign(doc.hash)

            magnet.write(signed_hash)
            magnet.close()
        return redirect('media', path=str(request.user.id)+'/'+magnet_filename)
    return redirect('main_app:start_page')


def magnet_file(request):
    # weryfikacja pliku magnetycznego
    if request.method == 'POST':
        form = MagnetFileForm(request.POST, request.FILES)
        if form.is_valid():
            lancuch = request.FILES['magnet_file'].read()
            lancuch = lancuch.decode("utf-8")  # konwersja kodowania z bytes na string utf-8

            # sprawdzenie podpisu
            signer = Signer()  # salt='jakas_sol'
            try:
                signed_hash = signer.unsign(lancuch)
            except BadSignature:
                print("Sign error !!!")
                messages.error(request,'Plik nie przeszedł weryfikacji.')
                return redirect('main_app:start_page')

            doc = Documents.objects.filter(hash=signed_hash).first()  # szukam pliku do ktorego kieruje magnet
            if doc and os.path.isfile("media/"+doc.file.name):
                data = {
                    'doc': doc,
                    "MEDIA_URL": MEDIA_URL
                }
                return render(request, 'main_app/Magnet_file_details.html', data)
            else:
                messages.warning(request,'Plik magnetyczny prowadzi do dokumentu, który już nie istnieje :( ')
                return render(request, 'main_app/Magnet_file_details.html')
        else:
            messages.error(request,'Maksymalny rozmiar 100 bajtów. Tylko pliki .magnet')
            print("Błędny formularz pliku magnetycznego !!!")
            return redirect('main_app:start_page')
    else:
        return redirect('main_app:start_page')

#
#
#
# ----------------------------------------------  API  ---------------------------------------------------------
#
#

@csrf_exempt
def api_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is None:
            return JsonResponse({"login": {"token": "error"}})

        tok, created = Tokens.objects.get_or_create(user=user)
        return JsonResponse({"login": {"token": tok.key}})
    else:
        return JsonResponse({"login": {"token":"error"}})

@csrf_exempt
def api_logout(request):
    if request.method == 'POST':
        try:
            token = Tokens.objects.get(key=request.POST.get('token'))
            token.delete()
            return JsonResponse({"logout":{"status":"ok"}})
        except Tokens.DoesNotExist:
            return JsonResponse({"logout":{"status":"error"}})
    else:
        return JsonResponse({"logout":{"status":"error"}})

@csrf_exempt
def api_register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')
        if User.objects.filter(username=username).exists():
            return JsonResponse({"register": {"status":"Username exists"}})

        new_user = User.objects.create_user(username, email, password, is_active=False)
        new_user.save()

        activation_code = hashlib.md5(email.encode('utf-8') + b'dUzOSoLi').hexdigest()
        subject = "Stamp service - Activation Code"
        text = (
            """
            Siemka {},
            \npotwierdz e-mail klikajac w link
            \n{}/account/activate/{}/{}/
            \nMasters of Masters
            """.format(username, request.get_host(), username, activation_code))

        send_mail(subject, text, EMAIL_HOST_USER, [email], fail_silently=False)  # wyslanie maila
        return JsonResponse({"register": {"status": "ok"}})

@csrf_exempt
def api_del_account(request):
    tok = Tokens.objects.get(key=request.POST.get('token'))
    if tok is None:
        return JsonResponse({"del":{"status": "error"}})
    user = tok.user
    user.is_active = False
    user.save()
    tok.delete()
    # user.delete()  # usuwa uzytkownika i wszystkie dane z nim powiazane
    return JsonResponse({"del":{"status": "ok"}})

@csrf_exempt
def api_change_mail(request):
    if request.method == 'POST' and request.POST['email']:
        tok = Tokens.objects.get(key=request.POST.get('token'))
        if tok is None:
            return JsonResponse({"mail":{"status": "error"}})
        new_email = request.POST.get('email')
        obj_user = tok.user
        obj_user.email = new_email
        obj_user.is_active = False  # uzytkownik bedzie musial potwierdzic nowego maila
        obj_user.save()
        username = obj_user.username

        #  to samo co podczas rejestracji: wysyla na maila link aktywacyjny

Aplikacja serwerowa i webowa/stamp_server/main_app/templates/main_app/Home_logged.html
{% extends 'main_app/base.html' %}

{% block middle %}
    <div class="container">
        <div class="row main_part">
            <div class="col-md-5 frame">
                <h3>Dodaj plik do systemu</h3>
                <form name = "form" enctype = "multipart/form-data" action = "{% url 'main_app:upload_file' %}" method = "POST" >
                    {% csrf_token %}
                    {{ uploadForm }}
                    <br/>
                    <button type="submit" class="btn btn-default">Wgraj</button>
                </form>
                <br/>
            </div>
            <div class="col-md-5 col-md-offset-2 frame">
                <h3>Wybierz plik magnetyczny</h3>
                <form name = "form" enctype = "multipart/form-data" action = "{% url 'main_app:magnet_file' %}" method = "POST" >
                    {% csrf_token %}
                    {{ magnetForm }}
                    <br/>
                    <button type="submit" class="btn btn-default">Sprawdź</button>
                </form>
                <br/>
            </div>
        </div>
    </div>

{% endblock %}

Aplikacja serwerowa i webowa/stamp_server/main_app/templates/main_app/Home_notLogged.html
{% extends 'main_app/base.html' %}


{% block middle %}
    <div class="row main_part">

        <div class="col-md-5 text-center">
            <h1>MagnetoDocs</h1>
        </div>
        <div class="col-md-5 col-md-offset-1 frame_notlogged">
            <h3>Wybierz plik magnetyczny</h3>
                <form name = "form" enctype = "multipart/form-data" action = "{% url 'main_app:magnet_file' %}" method = "POST" >
                    {% csrf_token %}
                    {{ magnetForm }}
                    <br/>
                    <button type="submit" class="btn btn-default">Sprawdź</button>
                </form>
            <br/>
        </div>

    </div>

{% endblock %}

Aplikacja serwerowa i webowa/stamp_server/main_app/templates/main_app/Magnet_file_details.html
{% extends 'main_app/base.html' %}

{% block middle %}
    <div class="row">
        <div class="container">
            {% if doc %}
            <h2>Znaleziono dokument</h2>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Nazwa dokumentu</th>
                            <th>Właściciel</th>
                            <th>Czas dodania pliku</th>
                            <th>Akcje</th>
                        </tr>
                    </thead>
                    <tbody>
                            <tr>
                                <td>{{ doc.filename }}</td>
                                <td>{{ doc.owner.username }}</td>
                                <td>{{ doc.timestamp|date:"j E o H:i:s"}}</td>
                                <td>
                                    <a href="{{ MEDIA_URL }}{{ doc.file.name }}" class="btn btn-success">Pobierz</a>
                                </td>
                            </tr>
                    </tbody>
                </table>
            {% endif %}
        </div>
    </div>
{% endblock %}

Aplikacja serwerowa i webowa/stamp_server/main_app/templates/main_app/archives.html
{% extends 'main_app/base.html' %}

{% block middle %}
    <div class="row">
        <div class="container">
            <h2>Archiwum dokumentów</h2>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Plik</th>
                            <th>Data dodania</th>
                            <th>Akcje</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for doc in docs %}
                            <tr>
                                <td>{{ doc.filename }}</td>
                                <td>{{ doc.date }}</td>
                                <td>
                                    <a href="{{ MEDIA_URL }}{{ doc.file.name }}" class="btn btn-success">Pobierz</a>
                                    <a href="{% url 'main_app:delete_file' doc.id %}" class="btn btn-danger">Usuń</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
        </div>
    </div>

{% endblock %}

Aplikacja serwerowa i webowa/stamp_server/main_app/templates/main_app/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% load static %}
    <link href="{% static 'main_app/css/base.css' %}" rel="stylesheet">
    <script src="{% static 'main_app/js/clock.js' %}" type="text/javascript"></script>

    <title>MagnetoDocs</title>
</head>
<body onload="startTime()">
    <nav class="navbar navbar-default navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>                        
                  </button>
                <a class="navbar-brand" href="{% url 'main_app:start_page' %}">MagnetoDocs</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                {% if user.is_authenticated %}
                    <ul class="nav navbar-nav navbar-right">
                            <li><a href="{% url 'main_app:start_page' %}">Strona główna</a></li>
                            <li><a href="{% url 'main_app:archives' %}">Archiwum</a></li>
                            <li><a href="{% url 'user_account:user_profile' %}">Mój profil</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'user_account:logout_view' %}">Wyloguj</a></li>
                    </ul>
                {% else %}
                    <ul class="nav navbar-nav navbar-right">
                        <li data-toggle="modal" data-target="#login"><a href="#">Logowanie</a></li>
                        <li data-toggle="modal" data-target="#register"><a href="#">Rejestracja</a></li>
                    </ul>
                {% endif %}
            </div>
        </div>
    </nav>
    {% if not user.is_authenticated %}
        {% include "user_account/login_and_register.html" %}
    {% endif %}

<div class="container-fluid">
    <!-- ZAGAR -->
    <div class="row">
        <div class="text-center">
            <div id="clock" style="font-size: 20pt;"></div>
        </div>
    </div>
    <div>
        {% if messages %}
                {% for message in messages %}
                  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                  </div>
                {% endfor %}
        {% endif %}
    </div>

    <!-- PANEL UZYTKOWNIKA -->
    {% block change_password_email_and_account_delete %}
    {% endblock %}

    <!-- CZESC GLOWNA -->
    {% block middle %}
    {% endblock %}


</div>

</body>
</html>

Aplikacja serwerowa i webowa/stamp_server/main_app/templates/main_app/descr_and_verify.html
{% extends 'main_app/base.html' %}

{% block description_and_verify %}
    <div class="row">

        <div class="col-md-6">
            [TUTAJ BEDZIE OPIS SERWISU]
        </div>
        <div class="col-md-6">
            [TUTAJ BEDZIE FORMULARZ SPRAWDZANIA PLIKU]
        </div>

    </div>

{% endblock %}

Aplikacja serwerowa i webowa/stamp_server/main_app/templates/main_app/sign_and_verify.html
{% extends 'main_app/base.html' %}

{% block description_and_verify %}
    <div class="container">
        <div class="row">
            <div class="col-md-5 frame">
                <h3>Dodaj plik do systemu</h3>
                <form name = "form" enctype = "multipart/form-data" action = "{% url 'main_app:upload_file' %}" method = "POST" >
                    {% csrf_token %}
                    {{ uploadForm }}
                    <br/>
                    <button type="submit" class="btn btn-default">Wyślij</button>
                </form>
                <br/>
            </div>
            <div class="col-md-5 col-md-offset-2 frame">
                <h3>Wybierz plik magnetyczny</h3>
                <form name = "form" enctype = "multipart/form-data" action = "{% url 'main_app:magnet_file' %}" method = "POST" >
                    {% csrf_token %}
                    {{ magnetForm }}
                    <br/>
                    <button type="submit" class="btn btn-default">Sprawdź</button>
                </form>
                <br/>
            </div>
        </div>
    </div>

{% endblock %}