Aplikacja serwerowa i webowa/stamp_server/main_app/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'main_app'
urlpatterns = [
    url(r'^$', views.start_page, name='start_page'),
    url(r'^user_account/', include("user_account.urls", namespace="user_account")),
    url(r'^archives/$', views.archives, name='archives'),
    url(r'^upload/$', views.upload_file, name='upload_file'),
    url(r'^magnet/$', views.magnet_file, name='magnet_file'),
    url(r'^archives/delete/(?P<file_id>[0-9]+)/$', views.delete_file, name='delete_file'),
    url(r'^download/magnet/(?P<file_id>[0-9]+)/$', views.download_magnet_file, name='download_magnet_file'),

    # API
    url(r'^api/login/$', views.api_login, name='api_login'),
    url(r'^api/logout/$', views.api_logout, name='api_logout'),
    url(r'^api/register/$', views.api_register, name='api_register'),
    url(r'^api/del_account/$', views.api_del_account, name='api_del_account'),
    url(r'^api/change_mail/$', views.api_change_mail, name='api_change_mail'),
    url(r'^api/change_password/$', views.api_change_password, name='api_change_password'),
    url(r'^api/archives/$', views.api_archives, name='api_archives'),
    url(r'^api/del_file/$', views.api_delete_file, name='api_delete_file'),
    url(r'^api/upload/$', views.api_upload_file, name='api_upload_file'),
    url(r'^api/download_magnet/$', views.api_download_magnet_file, name='api_download_magnet_file'),
    url(r'^api/check_magnet/$', views.api_check_magnet, name='api_check_magnet'),
    url(r'^api/download_file/$', views.api_download_file, name='api_download_file'),
    url(r'^api/check_magnet2/$', views.api_check_magnet2, name='api_check_magnet2'),
    url(r'^api/download_file2/$', views.api_download_file2, name='api_download_file2'),
]

Aplikacja serwerowa i webowa/stamp_server/stamp_server/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from .settings import MEDIA_ROOT, MEDIA_URL, DEBUG
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('user_account.urls')),
    url(r'^', include('main_app.urls'))  # od razu po wejsci kieruje do main_app.urls
]

if DEBUG:
    # umozliwia serwowanie statycznych plikow z katalogu media
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT,}, name='media'),
    ]

Aplikacja serwerowa i webowa/stamp_server/user_account/urls.py
from django.conf.urls import url

from . import views

app_name = 'user_account'
urlpatterns = [
    url(r'^login/$', views.login_view, name='login_view'),
    url(r'^logout/$', views.logout_view, name='logout_view'),
    url(r'^register/$', views.register_view, name='register_view'),
    url(r'^activate/(?P<username>[\w\d]+)/(?P<activation_code>[\w\d]+)/$',views.activate,name='activate'),
    url(r'^$', views.user_profile, name='user_profile'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^change_email/$', views.change_email, name='change_email'),
    url(r'^account_delete/$', views.account_delete, name='account_delete'),
]

# pierwszy argument (regular expression r'') to adres widoczny dla uzytkownika
# jest niezalezny od name'a :)

Aplikacja serwerowa i webowa/stamp_server/user_account/models.py
from django.db import models

# Create your models here.

Aplikacja serwerowa i webowa/stamp_server/user_account/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash  # for authenticate user
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User  # zarzadzanie uzytkownikami
from django.core.mail import send_mail  # wysylanie maili
from django.contrib.auth.forms import PasswordChangeForm  # wbudowany formularz zmiany hasla

from django.contrib import messages  # powiadomienia, ktore mozna wyswietlic w HTMLu
import hashlib  # do generowania activation_code

from stamp_server.settings import EMAIL_HOST_USER  # import maila tej apki
HOST_NAME = "127.0.0.1:8000"  # potrzebne podczas generowanie linku aktywacyjnego przy rejestracji


def login_view(request):
    """
    metoda logowania
    """
    if request.method == "POST":
        username = request.POST.get('username')  # to samo co request.POST['username']
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        #  sprawdzenie czy haslo pasuje do uzytkownika
        if user is not None:
            login(request, user)
        else:
            messages.error(request, 'Błędny login lub hasło.')
    return redirect('main_app:start_page')  # bez wzgledu na wynik logowania przekirowanie do glownej

@login_required(login_url='/')
def logout_view(request):
    logout(request)
    return redirect('main_app:start_page')

def register_view(request):
    """
    rejestracja uzytkownikow - na adres e-mail wysylany jest link aktywacyjny
    """
    if request.method == "POST":
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        # haslo w bazie zapisywane jest w formacie <algorithm>$<iterations>$<salt>$<hash> i używa PBKDF2
        # https://docs.djangoproject.com/en/1.10/ref/settings/#std:setting-PASSWORD_HASHERS

        # sprawdzenie czy uzytkownik o podanym 'username' juz istnieje
        if User.objects.filter(username=username).exists():
            messages.error(request, 'Użytkownik o podanej nazwie już istnieje.')
            return redirect('main_app:start_page')  # juz taki username istnieje

        new_user = User.objects.create_user(username, email, password, is_active=False)
        new_user.save()

        #  generowanie kodu aktywacyjnego: skrot MD5 nazwy uzytkownika+jakis tekst
        activation_code = hashlib.md5(email.encode('utf-8')+b'dUzOSoLi').hexdigest()
        subject = "Stamp service - Activation Code"
        text = (
            """
            Siemka {},
            \npotwierdz e-mail klikajac w link
            \n{}/account/activate/{}/{}/
            \nMasters of Masters
            """.format(username, request.get_host(), username, activation_code))

        send_mail(subject, text, EMAIL_HOST_USER, [email], fail_silently=False)  # wyslanie maila
        messages.info(request,'Kliknij w link aktywacyjny wysłany na podany adres e-mail.')
    return redirect('main_app:start_page')

def activate(request, username, activation_code):
    """
    metoda do aktywowania konta uzytkownika
    """
    user = get_object_or_404(User, username=username)
    if activation_code == hashlib.md5(user.email.encode('utf-8')+b'dUzOSoLi').hexdigest():
        user.is_active = True
        user.save()  # django domyslnie update'uje krotke, chyba ze wymusimy utworzenie nowej
        logout(request)  # wylogowanie user'a, bo klikniecie w link aktywacyjny od razu go loguje tez
        messages.success(request, 'Aktywacja konta udana.')
    else:
        messages.error(request, 'Aktywacja konta nie udała się.')
    
    return redirect('main_app:start_page')

@login_required(login_url='/')
def user_profile(request):
    """
    metoda wyswietlajaca HTML'a z formularzami do zmiany hasla, maila i usuniecie konta
    """
    return render(request, 'user_account/user_profile.html')

@login_required(login_url='/')
def change_password(request):
    if request.method == 'POST' and request.POST['old_password'] and request.POST['new_pass1'] \
            and request.POST['new_pass2']:  # sprawdzenie czy wszystkie pola zostaly uzupelnione
        old_password = request.POST.get('old_password')
        user = authenticate(username=request.user, password=old_password)
        # sprawdza stare haslo user'a
        # authenticate zwraca obiekt 'User' jesli haslo pasuje do uzytkownika, else zwraca None
        if user is None:
            messages.error(request, 'Podano złe aktualne hasło!')
            return redirect('user_account:user_profile')
        new_pass1 = request.POST.get('new_pass1')
        new_pass2 = request.POST.get('new_pass2')
        if new_pass1 != new_pass2:
            messages.error(request, 'Wpisz nowe hasło dwukrotnie!')
            return redirect('user_account:user_profile')
            pass
        user.set_password(new_pass1)
        user.save()
        update_session_auth_hash(request, user)  # aktualizacja biezacej sesji dla user'a z nowym haslem
        messages.success(request, 'Zmiana hasła powiodła się.')
    else:
        messages.error(request, 'Żadne pole hasła nie może być puste!')
    return redirect('user_account:user_profile')

@login_required(login_url='/')
def change_email(request):
    if request.method == 'POST' and request.POST['email']:
        new_email = request.POST.get('email')
        obj_user = get_object_or_404(User, username=request.user)
        obj_user.email = new_email
        obj_user.is_active = False  # uzytkownik bedzie musial potwierdzic nowego maila
        obj_user.save()
        username = obj_user.username

        #  to samo co podczas rejestracji: wysyla na maila link aktywacyjny
        activation_code = hashlib.md5(new_email.encode('utf-8') + b'dUzOSoLi').hexdigest()
        subject = "Stamp service - Change email - activation"
        text = (
            """
            Siemka {},
            \npotwierdz e-mail klikajac w link
            \n{}/account/activate/{}/{}/
            \nMasters of Masters
            """.format(username, request.get_host(), username, activation_code))

        send_mail(subject,text,EMAIL_HOST_USER,[new_email],fail_silently=False)  # wyslanie maila
        logout(request)
        messages.success(request, 'Zmiana adresu e-mail powiodła się.')
        return redirect('main_app:start_page')
    else:
        messages.error(request, 'Adres e-mail nie może być pusty!')
        return redirect('user_account:user_profile')


@login_required(login_url='/')
def account_delete(request):
    user = get_object_or_404(User, username=request.user)
    user.is_active = False  # TODO: usuwac czy deaktywowac uzytkownika??
    user.save()
    # user.delete()  # usuwa uzytkownika i wszystkie dane z nim powiazane
    logout(request)
    messages.success(request, 'Usunięto konto.')
    return redirect('main_app:start_page')

Aplikacja serwerowa i webowa/stamp_server/user_account/templates/user_account/login_and_register.html
<!-- lOGIN MODAL -->
    <div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="loginLabel">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="loginLabel">Logowanie</h4>
                </div>
                <form class="form-signin" action="{% url 'user_account:login_view' %}" method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="username" class="control-label">Nazwa użytkownika:</label>
                            <input type="text" class="form-control" name="username" required>
                        </div>
                        <div class="form-group">
                            <label for="password" class="control-label">Hasło:</label>
                            <input type="password" class="form-control" name="password" required>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
                        <button type="submit" class="btn btn-primary">Zaloguj</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- REGISTRATION MODAL -->
    <div class="modal fade" id="register" tabindex="-1" role="dialog" aria-labelledby="registerLabel">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="registerLabel">Rejestracja</h4>
                </div>
                <form class="form-signin" action="{% url 'user_account:register_view' %}" method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="username" class="control-label">Nazwa użytkownika:</label>
                            <input type="text" class="form-control" name="username" required>
                        </div>
                        <div class="form-group">
                            <label for="email" class="control-label">Adres e-mail:</label>
                            <input type="email" class="form-control" name="email" required>
                        </div>
                        <div class="form-group">
                            <label for="password" class="control-label">Hasło:</label>
                            <input type="password" class="form-control" name="password" required>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
                        <button type="submit" class="btn btn-primary">Zarejestruj</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

Aplikacja serwerowa i webowa/stamp_server/user_account/templates/user_account/user_profile.html
{% extends 'main_app/base.html' %}

<!--  Nie ruszac parametrow !! czyli nawiasow klamrowych oraz name='' -->

{% block change_password_email_and_account_delete %}
<div class="user_profile">
        <h3>Zmiana hasła</h3>
        <form action="{% url 'user_account:change_password' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="old_password">Aktualne hasło:</label>
                <input type="password" class="form-control" id="old_password" name="old_password">
            </div>
            <div class="form-group">
                <label for="new_pass1">Nowe hasło:</label>
                <input type="password" class="form-control" id="new_pass1" name="new_pass1">
            </div>
            <div class="form-group">
                <label for="new_pass2">Nowe hasło:</label>
                <input type="password" class="form-control" id="new_pass2" name="new_pass2">
            </div>
                <button type="submit" class="btn btn-default">Zmień hasło</button>
        </form>
    <hr>
        <h3>Zmiana adresu e-mail <small>(wymaga ponownej aktywacji)</small></h3>
        <form action="{% url 'user_account:change_email' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="email">E-mail:</label>
                <input type="email" class="form-control" id="email" name="email" value="{{ request.user.email }}">
            </div>
                <button type="submit" class="btn btn-default">Zmień e-mail</button>
        </form>
        <hr>
        <form action="{% url 'user_account:account_delete' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-default center-block">Usuń konto</button>
        </form>
</div>
{% endblock %}